### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by joliss** [myfreeweb/broccoli-rsvg#1]
Hey Greg,

Nice plugin! I believe there is no caching at the moment, right? This is going to get very slow as you add more SVG files, as they will all be re-converted on every rebuild.

You couldn't use broccoli-filter because you are emitting more than one output file per input file, correct? I wonder if we should extend the broccoli-filter class to handle multiple output files, or something.

Jo

**Comment by valpackett** [comment]
Yeah, that would be awesome :-)

**Comment by valpackett** [comment]
Hey @joliss, I've also noticed that we should invalidate the cache when the plugin's settings in the Brocfile change... It's not that noticeable in, like, minifiers, but with SVG rendering... change the size or transform and the image is still cached :-(

**Comment by joliss** [comment]
We cannot reliably detect changes in Brocfile, since we'd also have to detect when dependent modules (that are require'd in Brocfile) change. I figured it's better not to try than to do it unreliably. So if you change Brocfile, you have to restart the server.

**Comment by valpackett** [comment]
But is the cache deleted on restart?

**Comment by joliss** [comment]
Yes it is. :)
